repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2.6.0
          - sqlmodel>=0.0.18
          - sqlalchemy[mypy]>=2.0.0
          - pydantic-settings>=2.2.0
          - types-boto3
        args: [--strict]
        exclude: ^(infra|frontend|scripts)/

  - repo: https://github.com/PyCQA/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        additional_dependencies:
          - pydantic>=2.6.0
          - sqlmodel>=0.0.18
        exclude: ^(infra|frontend|scripts)/
